-- general {
--     disable_loading_bar = true
--     grace = 300
--     hide_cursor = true
--     no_fade_in = false
-- }
--
-- background {
--     monitor =
--     path = ~/Pictures/wallpapers/wall2.png   # Change to your wallpaper path
--     blur_passes = 1
--     blur_size = 5
-- }
--
-- input-field {
--     monitor =
--     size = 200, 50
--     position = 0, -160
--     dots_center = true
--     fade_on_empty = true
--     font_color = rgb(202, 211, 245)
--     inner_color = rgb(91, 96, 120)
--     outer_color =  rgba(33ccffee) rgba(00ff99ee) 45deg
--
--     outline_thickness = 5
--     placeholder_text = <span foreground="##cad3f5">Password...</span>
--     shadow_passes = 2
-- }
--
-- label {
--     monitor =
--     text = Hi there, $USER
--     color = rgba(200, 200, 200, 1.0)
--     font_size = 55
--     font_family = Noto Sans
--     position = 0, 160
--     halign = center
--     valign = center
-- }
--
-- label {
--     monitor =
--     text = $TIME
--     color = rgba(200, 200, 200, 1.0)
--     font_size = 100
--     font_family = Noto Sans
--     position = 0, 0
--     halign = center
--     valign = center
-- }
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: $HOME/.config/hypr/mocha.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.mocha")

local accent = mauve
local accentAlpha = mauveAlpha
local font = "JetBrainsMono Nerd Font"

-- GENERAL

-- TODO: manual review — unknown section 'background {' on line 64

-- TODO: manual review — unknown section 'label {' on line 72

-- TODO: manual review — unknown section 'label {' on line 84

-- TODO: manual review — unknown section 'image {' on line 97

-- TODO: manual review — unknown section 'input-field {' on line 109
hl.config({
	general = {
		disable_loading_bar = true,
		hide_cursor = true,
	},
	-- BACKGROUND
	-- TIME
	-- DATE
	-- USER AVATAR
	-- INPUT FIELD
})
