-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- In your main hyprland.conf
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/config/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.keybinds")
-- Source: ~/.config/hypr/config/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.monitors")
-- Source: ~/.config/hypr/config/auto_start.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.auto_start")

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("HYPRSHOT_DIR", "$HOME/Pictures/Screenshots/")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")
hl.env("XDG_DATA_DIRS", "/home/ghostvox/.local/share:/usr/local/share:/usr/share")
hl.env("CHROME_EXECUTABLE", "/usr/bin/chromium")

hl.permission({ binary = "/usr/(bin|local/bin)/grim", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/(bin|local/bin)/hyprpm", type = "plugin", mode = "allow" })

hl.window_rule({
	name = "pacman-update",
	match = {
		class = "^(pacman-update)$",
	},
	float = true,
	center = true,
	stay_focused = true,
})

hl.window_rule({
	name = "jetbrains-toolbox",
	match = {
		class = "^(jetbrains-.*)$",
		title = "^(win[0-9]+)$",
	},
	no_focus = true,
})

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
	leaf = "global",
	enabled = true,
	speed = 10,
	bezier = "default",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 5.39,
	bezier = "easeOutQuint",
})
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 4.79,
	bezier = "easeOutQuint",
})
hl.animation({
	leaf = "windowsIn",
	enabled = true,
	speed = 4.1,
	bezier = "easeOutQuint",
	style = "popin 87%",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 1.49,
	bezier = "linear",
	style = "popin 87%",
})
hl.animation({
	leaf = "fadeIn",
	enabled = true,
	speed = 1.73,
	bezier = "almostLinear",
})
hl.animation({
	leaf = "fadeOut",
	enabled = true,
	speed = 1.46,
	bezier = "almostLinear",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 3.03,
	bezier = "quick",
})
hl.animation({
	leaf = "layers",
	enabled = true,
	speed = 3.81,
	bezier = "easeOutQuint",
})
hl.animation({
	leaf = "layersIn",
	enabled = true,
	speed = 4,
	bezier = "easeOutQuint",
	style = "fade",
})
hl.animation({
	leaf = "layersOut",
	enabled = true,
	speed = 1.5,
	bezier = "linear",
	style = "fade",
})
hl.animation({
	leaf = "fadeLayersIn",
	enabled = true,
	speed = 1.79,
	bezier = "almostLinear",
})
hl.animation({
	leaf = "fadeLayersOut",
	enabled = true,
	speed = 1.39,
	bezier = "almostLinear",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 1.94,
	bezier = "almostLinear",
	style = "fade",
})
hl.animation({
	leaf = "workspacesIn",
	enabled = true,
	speed = 1.21,
	bezier = "almostLinear",
	style = "fade",
})
hl.animation({
	leaf = "workspacesOut",
	enabled = true,
	speed = 1.94,
	bezier = "almostLinear",
	style = "fade",
})
hl.animation({
	leaf = "zoomFactor",
	enabled = true,
	speed = 7,
	bezier = "quick",
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

hl.window_rule({
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

hl.window_rule({
	name = "xwayland-drag-fix",
	match = {
		class = "^$",
		title = "^$",
		xwayland = 1,
		float = true,
	},
})

hl.window_rule({
	name = "intellij-floating-focus",
	match = {
		class = "^(jetbrains-.*)$",
		title = "^$",
	},
	center = true,
	stay_focused = true,
})

hl.window_rule({
	name = "intellij-toolbox",
	match = {
		class = "(jetbrains-toolbox)",
		title = "(Toolbox)",
	},
	monitor = "HDMI-A-1",
})

hl.window_rule({
	name = "file-pickers",
	match = {
		class = "^(xdg-desktop-portal-gtk)$",
	},
	float = true,
	center = true,
	size = "60% 60%",
})

hl.env("HYPRLAND_SHARE_PICKER", "~/.local/bin/hypr-share-picker")
hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
	-- This line will be changed by your script
	--############################
	--## ENVIRONMENT VARIABLES ###
	--############################
	-- See https://wiki.hypr.land/Configuring/Environment-variables/
	--##################
	--## PERMISSIONS ###
	--##################
	-- See https://wiki.hypr.land/Configuring/Permissions/
	-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
	-- for security reasons
	ecosystem = {
		enforce_permissions = 0,
	},
	--####################
	--## LOOK AND FEEL ###
	--####################
	-- Refer to https://wiki.hypr.land/Configuring/Variables/
	-- https://wiki.hypr.land/Configuring/Variables/#general
	general = {
		gaps_in = 4,
		gaps_out = 2,
		border_size = 2,
		-- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
		col = {
			active_border = { colors = { "rgba(8FBDC9ee)", "rgba(2F6B85ee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,
		-- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
	},
	-- https://wiki.hypr.land/Configuring/Variables/#decoration
	decoration = {
		rounding = 10,
		rounding_power = 2,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.9,
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
		-- https://wiki.hypr.land/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 8,
			passes = 2,
			vibrancy = 0.1696,
			new_optimizations = true,
		},
	},
	-- Window Rules
	-- Rules for the custom Pacman update terminal
	-- JetBrains Focus Window Rule
	-- https://wiki.hypr.land/Configuring/Variables/#animations
	animations = {
		enabled = true,
		-- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
		--        NAME,           X0,   Y0,   X1,   Y1
		-- Default animations, see https://wiki.hypr.land/Configuring/Animations/
		--           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
	},
	-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
	-- "Smart gaps" / "No gaps when only"
	-- uncomment all if you wish to use that.
	-- workspace = w[tv1], gapsout:0, gapsin:0
	-- workspace = f[1], gapsout:0, gapsin:0
	-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
	-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]
	-- windowrule = bordersize 0, floating:0, onworkspace:f[1]
	-- windowrule = rounding 0, floating:0, onworkspace:f[1]
	-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
	dwindle = {
		preserve_split = true, -- You probably want this
	},
	-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
	master = {
		new_status = "master",
	},
	-- https://wiki.hypr.land/Configuring/Variables/#misc
	misc = {
		force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
	},
	--############
	--## INPUT ###
	--############
	-- https://wiki.hypr.land/Configuring/Variables/#input
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		-- changes the behavior of auto selecting window mouse is hovering over.
		follow_mouse = 1,
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = true,
		},
	},
	-- See https://wiki.hypr.land/Configuring/Gestures
	-- Example per-device config
	-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
	--#############################
	--## WINDOWS AND WORKSPACES ###
	--#############################
	-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
	-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
	-- Example windowrule
	-- windowrule = float,class:^(kitty)$,title:^(kitty)$
	-- Ignore maximize requests from apps
	-- Fix XWayland dragging issues
	-- Auto Focus floating Intellij windows
	--
	-- Window rules to make file pickers appear infront of fullscreen apps
	-- hypr-share-picker
})
