-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local terminal = "kitty"
local fileManager = "nautilus"
local browser = "chromium --ozone-platform=wayland --enable-features=UseOzonePlatform,WaylandWindowDecorations"

-- Core Display/D-Bus Environment Setup

-- Core Desktop Shell (Launches top bars, panel daemons, notification handlers, and clipboard managers)

-- Hardware & Connectivity Applets

-- System Management

-- Compositor Plugins

-- ─────────────────────────────────────────────────────────────────
-- ─── REMOVED/CLEANED SERVICES (No longer needed with Noctalia) ───
-- ─────────────────────────────────────────────────────────────────
-- exec-once = sleep 1 && hyprpaper                 # Handled natively by Noctalia
-- exec-once = swaync                                # Handled natively by Noctalia
-- exec-once = wl-paste --watch cliphist store       # Handled natively by Noctalia

-- Optional Workspace Initializers
-- exec-once = $terminal
-- exec-once = $browser
--exec-once = blueman-applet

hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("noctalia -d")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("hypridle")
	hl.exec_cmd('hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"')
	hl.exec_cmd("hyprpm reload -n")
end)
