# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$browser = firefox
# Or execute your favorite apps at launch like this:
 exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
 exec-once = $terminal
 exec-once= $browser
exec-once = noctalia
# Start the clipboard history daemon
exec-once = wl-paste --watch cliphist store
# load all the plugins you installed
exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"
exec-once = hyprpm reload -n
