-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local terminal = "ghostty"
local fileManager = "nautilus"
local browser = "chromium"
local menu = "walker"

--##################
--## KEYBINDINGS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier
local MOD = "CTRL"

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("kitty --config $HOME/.config/kitty/kitty.conf"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + G", hl.dsp.window.float({ action = "toggle" }))
--bind = $mainMod, space, exec, $menu # open application menu
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + b", hl.dsp.exec_cmd("firefox"))

-- ─────────────────────────────────────────────────────────────────
-- ─── STATUS BAR & SHELL SWITCH (Waybar vs Noctalia v5) ───────────
-- ─────────────────────────────────────────────────────────────────

-- ---> INACTIVE: OLD WAYBAR, SWAYNC, ROFI, & CLIPHIST UTILITIES
-- (Commented out to prevent conflicts with the new shell environment)
-- bind = $mainMod, R, exec, ~/.config/waybar/scripts/reload.sh # reload waybar
-- bind = SUPER, N, exec, swaync-client -t -sw # toggle swaync
-- bind = $mainMod, backspace,exec, pkill rofi || ~/.config/rofi/launchers/launcher.sh
-- bind = $mainMod, slash, exec, pkill rofi || ~/.config/rofi/cheatsheet/cheatsheet.sh
-- bind = SUPER, W, exec, pkill rofi || ~/.config/rofi/wallselector/wallpaper-picker.sh
-- bind = $mainMod, DELETE, exec, pkill rofi ||  ~/.config/rofi/powermenu/powermenu.sh
-- bind = $mainMod, V, exec, cliphist list | rofi -dmenu -p "Clipboard History:" | cliphist decode | wl-copy
-- bind = $mainMod, X, exec, pkill rofi || ~/.config/rofi/pomodoro/pomodoro.sh
-- bind = $mainMod, period, exec, pkill rofi || ~/.config/rofi/emoji/emoji.sh

-- ---> ACTIVE: NOCTALIA v5 NATIVE BINDINGS
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("noctalia msg config-reload"))
hl.bind(mainMod .. " + backspace", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("noctalia msg panel-toggle control-center"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("noctalia msg panel-toggle clipboard"))
hl.bind(mainMod .. " + DELETE", hl.dsp.exec_cmd("noctalia msg panel-toggle session"))
hl.bind(mainMod .. " + Tab", hl.dsp.exec_cmd("noctalia msg window-switcher"))
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("noctalia msg plugin official/keybind-cheatsheet panel toggle"))
hl.bind("SUPER + W", hl.dsp.exec_cmd("noctalia msg panel-toggle wallpaper"))
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("noctalia msg panel-open launcher /emo"))
hl.bind(MOD .. " + SHIFT + 3", hl.dsp.exec_cmd("noctalia msg screenshot-region"))
hl.bind(MOD .. " + SHIFT + 5", hl.dsp.exec_cmd("noctalia msg plugin noctalia/screen_recorder:service all toggle"))
-- Fast Audio Output Switchers (Bypasses Noctalia's UI Filter Bug)
hl.bind(
	mainMod .. " + H",
	hl.dsp.exec_cmd(
		'wpctl set-default 88 && noctalia msg notification-send "Audio Output" "Switched to Sony WH-1000XM5"'
	)
)
hl.bind(
	mainMod .. " + u",
	hl.dsp.exec_cmd('wpctl set-default 34 && noctalia msg notification-send "Audio Output" "Switched to Corsair HS80"')
)
-- ─────────────────────────────────────────────────────────────────

-- ─── Pomodoro timer ─────────────────────────────────────────────
hl.bind(mainMod .. " + a", hl.dsp.exec_cmd("hyprctl dispatch hyprmodoro:start"))
hl.bind(mainMod .. " + SHIFT + a", hl.dsp.exec_cmd("hyprctl dispatch hyprmodoro:stop"))

-- --- Enter fullscreen mode ---
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
-- --- Have Screen Read Selected Text Aloud ---
hl.bind(mainMod .. " + i", hl.dsp.exec_cmd("~/.config/Dot_Files/hypr/read.sh"))

hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd("~/.config/Dot_Files/hypr/discord_read.sh"))

-- ─── General Menus & Utilities ──────────────────────────────────
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("noctalia msg panel-toggle control-center"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("qalculate-gtk"))

--bind = $MOD SHIFT, 3, exec, $HOME/.config/hypr/screenshot.sh 3
hl.bind(MOD .. " + SHIFT + 4", hl.dsp.exec_cmd("$HOME/.config/hypr/screenshot.sh 4"))

-- Take video recording of screen using wf-recorder
--bind = $MOD SHIFT, 5, exec, ~/.config/hypr/toggle-record.sh # Start/stop screen recording

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + e", hl.dsp.exec_cmd("thunderbird"))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
-- Swap window left
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))

-- Swap window right
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

-- Swap window up
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))

-- Swap window down
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(mainMod .. " + End", hl.dsp.exec_cmd("~/.config/hypr/brightness.sh -"), { repeating = true })
hl.bind(mainMod .. " + Home", hl.dsp.exec_cmd("~/.config/hypr/brightness.sh +"), { repeating = true })
-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
