--###############
--## MONITORS ###
--###############

-- ASUS 1440p (Left Monitor)
-- Positioned at 0x0
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "desc:ASUSTek COMPUTER INC VG27AQL1A R3LMQS077872",
	mode = "2560x1440@60",
	position = "0x0",
	scale = "1",
})

-- Dell 4K (Right Monitor)
-- Positioned at 2560x0 (Width of the ASUS)
hl.monitor({
	output = "desc:Dell Inc. DELL S2725QC GZPG464",
	mode = "3840x2160@60",
	position = "2560x0",
	scale = "1.5",
})

-- Set to native 4K resolution, 100Hz+ if cable supports it, at position 2560x0, scale 1.6
--monitor = HDMI-A-2, 3840x2160@60, 2560x0, 1.6

-- ASUS 1440p Monitor (Left)
-- Set to native resolution and max refresh rate (144Hz), at position 0x0, scale 1

--monitor = DP-6, 2560x1440@144, 0x0, 1
-- Alternative Portait mode
--monitor = HDMI-A-2, 3840x2160@60, 1440x0, 1.6
--monitor = DP-6, 2560x1440@144, 0x0, 1, transform, 1
